### ISSUE TITLE
process_companies 수행 시 MemoryError

### ISSUE THREAD

**Issue by willbelucky** [willbelucky/ksif_preprocessing#3]
> processed_companies = process_companies(filtered_companies)
C:\Users\willbe\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops.py:1037: RuntimeWarning: divide by zero encountered in true_divide
  lambda x: op(x, rvalues))
C:\Users\willbe\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops.py:1037: RuntimeWarning: invalid value encountered in true_divide
  lambda x: op(x, rvalues))
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 365, in _on_run
    r = self.sock.recv(1024)
ConnectionAbortedError: [WinError 10053] 현재 연결은 사용자의 호스트 시스템의 소프트웨어의 의해 중단되었습니다
Traceback (most recent call last):
  File "C:\Users\willbe\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops.py", line 1033, in safe_na_op
    return na_op(lvalues, rvalues)
  File "C:\Users\willbe\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops.py", line 1012, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "C:\Users\willbe\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\computation\expressions.py", line 205, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "C:\Users\willbe\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\computation\expressions.py", line 120, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "C:\Users\willbe\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\computation\expressions.py", line 65, in _evaluate_standard
    return op(a, b)
ZeroDivisionError: float division by zero
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\willbe\AppData\Local\Programs\Python\Python36\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\willbe\PycharmProjects\ksif_preprocessing\core\data_processor.py", line 126, in process_companies
    available_companies[PSR] = available_companies[MKTCAP] / available_companies.sales12 / 1000
  File "C:\Users\willbe\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops.py", line 1069, in wrapper
    result = safe_na_op(lvalues, rvalues)
  File "C:\Users\willbe\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops.py", line 1037, in safe_na_op
    lambda x: op(x, rvalues))
  File "pandas\_libs\algos_common_helper.pxi", line 1212, in pandas._libs.algos.arrmap_object
  File "C:\Users\willbe\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\ops.py", line 1037, in <lambda>
    lambda x: op(x, rvalues))
MemoryError

문제 라인이 실행될 때 메모리가 지속적으로 증가하다가 메모리가 초과되며 프로그램이 강제종료 됨.

**Comment by willbelucky** [comment]
## Trial 1
- 원인: Series끼리 나누기를 할 때 ZeroDivisionError가 발생할 경우 Pandas 내에서 에러를 처리하려다가 무한루프를 돌며 뭔가를 저장하여 결국 메모리를 모두 사용한다.
- 해결책: 외부에서 ZeroDivisionError를 방어할 수 있는 코드를 작성한다. zero_to_nan 함수를 만들어 Series 간의 나눗셈 연산의 분모에 적용하였다.
- 결과: 위의 문제 해결되었다.
